import { StyleSheet } from 'react-native';

import { T } from '../../theme';

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: T.bg },
  phaseBar: { flexDirection: 'row', gap: 4, paddingHorizontal: 20, paddingTop: 52 },
  phaseSegment: { flex: 1, height: 3, borderRadius: 2 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  closeBtn: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  closeText: { color: T.sub, fontSize: 16 },
  phaseLabel: { fontSize: 14, fontWeight: '700' },
  xpPill: { backgroundColor: T.goldBg, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  xpText: { color: T.gold, fontSize: 11, fontWeight: '700' },

  phaseContent: { flex: 1, padding: 20, justifyContent: 'center' },
  scrollPhase: { flex: 1 },
  scrollContent: { padding: 20 },

  hookCard: {
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    marginBottom: 20,
    alignItems: 'center',
  },
  hookEmoji: { fontSize: 36, marginBottom: 10 },
  hookText: { fontSize: 17, fontWeight: '700', textAlign: 'center', lineHeight: 26 },
  lessonTitle: {
    color: T.text,
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 10,
  },
  metaRow: { flexDirection: 'row', gap: 16, justifyContent: 'center', marginBottom: 24 },
  metaItem: { color: T.sub, fontSize: 13, fontWeight: '600' },

  conceptTitle: { color: T.text, fontSize: 20, fontWeight: '800', marginBottom: 14 },
  conceptBold: { fontSize: 15, fontWeight: '800', marginBottom: 4 },
  conceptBody: { color: T.text, fontSize: 14, lineHeight: 22, marginBottom: 6 },
  bulletRow: { flexDirection: 'row', gap: 8, marginBottom: 4, paddingLeft: 4 },
  bulletDot: { fontSize: 14, fontWeight: '800', lineHeight: 22 },
  bulletText: { color: T.text, fontSize: 14, lineHeight: 22, flex: 1 },
  inlineBold: { fontWeight: '800' },

  taskInstruction: { color: T.text, fontSize: 15, fontWeight: '700', marginBottom: 14 },
  hintBox: { borderRadius: 10, padding: 8, borderWidth: 1, marginBottom: 10 },
  hintText: { fontSize: 12, fontWeight: '600' },
  categoriesWrap: { gap: 10, marginBottom: 14 },
  categoryBucket: { backgroundColor: T.surface, borderRadius: 14, padding: 12, borderWidth: 2 },
  categoryLabel: { fontSize: 13, fontWeight: '800', marginBottom: 8 },
  categoryItems: { gap: 6, minHeight: 36 },
  assignedItem: { borderRadius: 8, padding: 8, borderWidth: 1, backgroundColor: T.card },
  assignedItemText: { color: T.text, fontSize: 12 },
  emptyBucket: {
    color: T.faint,
    fontSize: 12,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 4,
  },
  poolTitle: { color: T.sub, fontSize: 12, marginBottom: 8 },
  itemsPool: { flexWrap: 'wrap', flexDirection: 'row', gap: 8, marginBottom: 16 },
  poolItem: {
    backgroundColor: T.surface,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: T.border,
  },
  poolItemText: { color: T.text, fontSize: 12 },

  sortHint: { color: T.sub, fontSize: 12, marginBottom: 10, fontStyle: 'italic' },
  sortRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: T.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: T.border,
    marginBottom: 8,
  },
  sortNum: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sortNumText: { color: '#000', fontSize: 11, fontWeight: '800' },
  sortItemText: { color: T.text, fontSize: 13, flex: 1 },
  sortArrows: { flexDirection: 'row', gap: 4 },
  arrowBtn: { padding: 4 },
  arrowText: { fontSize: 16, fontWeight: '700' },

  resultBox: { borderRadius: 12, padding: 14, marginBottom: 14 },
  resultText: { fontSize: 14, fontWeight: '700' },

  questionBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  questionBadgeText: { fontSize: 12, fontWeight: '700' },
  questionText: {
    color: T.text,
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 26,
    marginBottom: 20,
  },
  optionsWrap: { gap: 10, marginBottom: 20 },
  option: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: T.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: T.border,
  },
  optCorrect: { borderColor: T.green, backgroundColor: T.greenBg },
  optWrong: { borderColor: T.red, backgroundColor: T.redBg },
  optLetter: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: T.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optLetterText: { color: T.text, fontSize: 12, fontWeight: '700' },
  optText: { color: T.sub, fontSize: 14, flex: 1, lineHeight: 20 },
  feedback: { borderRadius: 14, padding: 14, marginBottom: 16 },
  fbOk: { backgroundColor: T.greenBg },
  fbFail: { backgroundColor: T.redBg },
  fbText: { fontSize: 13, lineHeight: 20 },

  // Consequence
  consequenceBanner: {
    borderRadius: 14,
    padding: 20,
    borderWidth: 2,
    marginBottom: 14,
    alignItems: 'center',
  },
  consequenceEmoji: { fontSize: 48, marginBottom: 8 },
  consequenceTitle: { fontSize: 20, fontWeight: '800', textAlign: 'center' },

  sceneCard: {
    backgroundColor: T.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    marginBottom: 14,
  },
  sceneLabel: { color: T.sub, fontSize: 11, fontWeight: '700', marginBottom: 6 },
  sceneText: { color: T.text, fontSize: 14, fontWeight: '600', marginBottom: 8 },
  impactText: { color: T.sub, fontSize: 13, lineHeight: 20 },

  pnlCard: {
    backgroundColor: T.card,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: T.border,
    marginBottom: 14,
  },
  pnlTitle: { color: T.text, fontSize: 13, fontWeight: '700', marginBottom: 10 },
  pnlRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  pnlLabel: { color: T.sub, fontSize: 13 },
  pnlValue: { fontSize: 13, fontWeight: '700' },

  penaltyBadge: {
    backgroundColor: T.redBg,
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: T.red + '55',
    marginBottom: 14,
  },
  penaltyText: { color: T.red, fontSize: 12, fontWeight: '600' },

  recoveryCard: {
    backgroundColor: T.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    marginBottom: 16,
  },
  recoveryLabel: { color: T.sub, fontSize: 11, fontWeight: '700', marginBottom: 4 },
  recoveryText: { color: T.text, fontSize: 13, lineHeight: 20 },

  // Verdict
  verdictWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
  xpCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: T.goldBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    borderWidth: 2,
    borderColor: T.gold,
  },
  xpCircleWrong: { backgroundColor: T.redBg, borderColor: T.red },
  xpCircleEmoji: { fontSize: 28, marginBottom: 2 },
  xpCircleNum: { fontSize: 28, fontWeight: '900' },
  xpCircleLabel: { color: T.gold, fontSize: 12, fontWeight: '700' },
  verdictTitle: { color: T.text, fontSize: 22, fontWeight: '800', marginBottom: 6 },
  verdictLesson: { color: T.sub, fontSize: 14, marginBottom: 16, textAlign: 'center' },
  retryHint: {
    backgroundColor: T.goldBg,
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    alignSelf: 'stretch',
  },
  retryHintText: { color: T.gold, fontSize: 12, textAlign: 'center', lineHeight: 18 },
  verdictBox: {
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    marginBottom: 28,
    alignSelf: 'stretch',
  },
  verdictText: { fontSize: 14, fontWeight: '600', textAlign: 'center', lineHeight: 22 },

  nextBtn: { borderRadius: 14, padding: 16, alignItems: 'center', marginTop: 8 },
  nextBtnText: { color: '#000', fontSize: 15, fontWeight: '700' },
});
